# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 08:52
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bod',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_no',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None),
        ),
    ]
