# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 09:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20170521_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to=settings.AUTH_USER_MODEL),
        ),
    ]
