# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_profile_karyakar_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='karyakar_type',
            field=models.CharField(choices=[('karyakar', 'karyakar'), ('nirikshak', 'nirikshak'), ('balkaryakar', 'balkaryakar'), ('visitor', 'visitor')], default='visitor', max_length=20),
        ),
    ]
