# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-03 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to=b'qrcode'),
        ),
    ]
