# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sabhatype',
            name='sabha_type',
            field=models.TextField(unique=True),
        ),
    ]
