# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 04:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0002_auto_20170512_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='SabhaSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[(b'active', b'active'), (b'close', b'close'), (b'pending', b'pending'), (b'removed', b'removed')], max_length=20)),
                ('sabhatype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.SabhaType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
