# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='leave_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
